name: valorantlab
description: A new Flutter project.
publish_to: "none"

version: 1.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  agent:
    path: features/agent
    
  home:
    path: features/home
    
  # Shared
  dependencies:
    path: shared/dependencies

  core:
    path: packages/core

dev_dependencies:
  melos: ^6.1.0
  commitlint_cli: ^0.7.1
flutter:
  uses-material-design: true
