name: valorantlab
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  agent:
    path: lib/features/agent
    
  # Shared
  dependencies:
    path: shared/dependencies

  core:
    path: packages/core

dev_dependencies:
  melos: ^5.2.2
  commitlint_cli: ^0.7.1
flutter:
  uses-material-design: true
