name: valorantlab
description: App that displays information about the game Valorant, including detail on Agents, Maps, Weapons, and more.
publish_to: "none"

version: 1.3.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  agent:
    path: features/agent
    
  home:
    path: features/home

  weapon:
    path: features/weapon
    
  # Shared
  dependencies:
    path: shared/dependencies
  i18n:
    path: shared/i18n

  core:
    path: packages/core

dev_dependencies:
  melos: ^6.0.0
  commitlint_cli: ^0.7.1
  flutter_launcher_icons: ^0.14.1
  flutter_flavorizr: 2.2.3

flutter:
  uses-material-design: true

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "launcher/ios-app-icon.png"
  image_path_android: "launcher/android-app-icon.png"
  adaptive_icon_background: "launcher/android-app-icon-background.png"
  adaptive_icon_foreground: "launcher/android-app-icon-foreground.png"
  remove_alpha_ios: true

flavorizr:
  ide: "vscode"
  app:
    android:
      flavorDimensions: "flavor-type"
    
  flavors:
    dev:
      app:
        name: "Valorantlab Dev"
      android:
        applicationId: "com.valorantlab.app.dev"
        icon: "launcher/android-app-icon-dev.png"
        adaptiveIcon:
          foreground: "launcher/android-app-icon-foreground-dev.png"
          background: "launcher/android-app-icon-background.png"
      ios:
        bundleId: "com.valorantlab.app.dev"
        icon: "launcher/ios-app-icon-dev.png"
    
    prod:
      app:
        name: "Valorantlab"
      android:
        applicationId: "com.valorantlab.app"  
        icon: "launcher/android-app-icon.png"
        adaptiveIcon:
          foreground: "launcher/android-app-icon-foreground.png"
          background: "launcher/android-app-icon-background.png"
      ios:
        bundleId: "com.valorantlab.app"
        icon: "launcher/ios-app-icon.png"