name: dependencies
description: "Dependencies of Valoranlab"
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^13.2.1
  http: ^1.2.0
  injectable: ^2.3.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  path_provider: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.8
  commitlint_cli: ^0.7.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  husky: ^0.1.7
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
