name: core
description: "A new Flutter package project."
version: 0.0.5
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  home:
    path: ../../features/home

  weapon:
    path: ../../features/weapon

  maps:
    path: ../../features/maps

  agent:
    path: ../../features/agent

  gear:
    path: ../../features/gear

  dependencies:
    path: ../../shared/dependencies
  i18n:
    path: ../../shared/i18n

dev_dependencies:
  build_runner: ^2.4.8
  injectable_generator: ^2.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/
  fonts:
    - family: Valorant
      fonts:
        - asset: assets/fonts/Valorant.ttf

flutter_gen:
  integrations:
    flutter_svg: true
  assets:
    outputs:
      package_parameter_enabled: true
  fonts:
    outputs:
      package_parameter_enabled: true