name: core
description: "A new Flutter package project."
version: 0.0.2
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  agent:
    path: ../../features/agent
    
  home:
    path: ../../features/home

  dependencies:
    path: ../../shared/dependencies

dev_dependencies:
  build_runner: ^2.4.8
  injectable_generator: ^2.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.3

flutter:
  assets:
    - assets/
    - assets/images/

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
 